POST http://localhost:8080/events
content-Type: application/json

{
        "name": "GO Bermuda", 
        "description": "This is a test event by bermuda", 
        "location": "Lagos, Nigeria",
        "dateTime": "2024-11-21T12:00:00Z"
}