POST http://localhost:8080/events
content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzMzMDM2MjE2LCJ1c2VySWQiOjJ9.5j-eMwDb4LZ0WEDyMqKItZAAE5K_KxBUwdKNhd1bC_E

{
        "name": "New event test test", 
        "description": "This is a test event by user 2 test", 
        "location": "Lagos, Nigeria",
        "dateTime": "2024-11-21T12:00:00Z"
}